# 12. Create a 3x3x3 array with random values

In [2]:
from numpy.random import default_rng
rng = default_rng(1234)
random_array = rng.random((3,3,3))
print(random_array)

[[[0.97669977 0.38019574 0.92324623]
  [0.26169242 0.31909706 0.11809123]
  [0.24176629 0.31853393 0.96407925]]

 [[0.2636498  0.44100612 0.60987081]
  [0.8636213  0.86375767 0.67488131]
  [0.65987435 0.7357577  0.22275366]]

 [[0.17206618 0.87041497 0.06013866]
  [0.68368891 0.67123802 0.61101798]
  [0.06013731 0.97776927 0.43895163]]]


In [6]:
import numpy as np
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.41432262 0.78150168 0.78157862]
  [0.39488698 0.37623119 0.10637587]
  [0.34311722 0.30150528 0.52794343]]

 [[0.22033045 0.360282   0.78697753]
  [0.91947256 0.84173847 0.20867691]
  [0.62356564 0.36806771 0.45688957]]

 [[0.96952637 0.43707663 0.80015264]
  [0.82199114 0.91105869 0.38630412]
  [0.32038403 0.61530161 0.21109486]]]
