# 15. Create a 2d array with 1 on the border and 0 inside

In [13]:
import numpy as np
array_2d = [[1, 1, 1, 1, 1, 1],[1, 0, 0,0, 0, 1], [1, 0, 0,0, 0, 1],[1, 0, 0,0, 0, 1],[1, 0, 0,0, 0, 1], [1, 1, 1,1, 1,1]]
array_need = np.array(array_2d)
print(array_need)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
