# 16. How to add a border (filled with 0's) around an existing array?

In [17]:
import numpy as np
array_2d = [[1, 1, 1,1, 1],[1, 1, 1,1, 1], [1, 1, 1,1, 1]]
array_original = np.array(array_2d)
print("Existing Array:")
print(array_original)
print("Array with a border filled with zeros")
array_need = [[0,0, 0, 0,0, 0,0],[0,1, 1, 1,1, 1,0],[0,1, 1, 1,1, 1,0],[0,1, 1, 1,1, 1,0],[0,1, 1, 1,1, 1,0], [0,0, 0, 0,0, 0,0]]
array_zero_border = np.array(array_need)
print(array_zero_border)

Existing Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Array with a border filled with zeros
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [25]:
Z = [[1, 1, 1,1,1, 1],[1, 1, 1,1,1, 1],[1, 1, 1,1,1, 1],[1,1, 1, 1,1, 1],[1,1, 1, 1,1, 1],[1,1, 1, 1,1, 1], [1,1, 1, 1,1, 1]]
Z = np.array(Z)
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
