# 21. Create a checkerboard 8x8 matrix using the tile function

In [6]:
matrix = np.tile( np.array([[0,1],[1,0]]), (4,4)) #Repeat 0, 1 four times and 1,0 four times
print(matrix)
#The numpy.tile() function constructs a new array by repeating array – ‘arr’,
#the number of times we want to repeat as per repetitions.

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
