# 22. Normalize a 5x5 random matrix

In [11]:
import numpy as np
a = np.random.random((25)).reshape(5,5)
row_sums = a.sum(axis=1)
new_matrix = a / row_sums[:, np.newaxis]
print(new_matrix)

#Broadcasting is really good for this

[[0.10040829 0.28767757 0.21983294 0.264507   0.12757421]
 [0.19578438 0.00653875 0.28068808 0.31686119 0.2001276 ]
 [0.27176649 0.56825741 0.05838532 0.06696531 0.03462547]
 [0.04361433 0.03577638 0.53069326 0.17290614 0.21700988]
 [0.21469032 0.13990908 0.20461782 0.00658363 0.43419915]]
