# 27. Consider an integer vector Z, which of these expressions are legal?

In [9]:
import numpy as np
Z = np.arange(1,11,1)
Z**Z

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408],
      dtype=int32)

In [10]:
2 << Z >> 2

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [11]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [12]:
1j*Z

array([0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j, 0. +7.j,
       0. +8.j, 0. +9.j, 0.+10.j])

In [13]:
Z/1/1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [17]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()