# 30. How to find common values between two arrays?

In [2]:
import numpy as np
array1 = np.random.randint(0,10,10)
print(array1)
array2 = np.random.randint(0,10,10)
print(array2)
print(np.intersect1d(array1,array2))

[4 9 6 9 5 7 3 2 4 8]
[4 9 1 6 1 8 5 5 9 4]
[4 5 6 8 9]
